### ISSUE TITLE
Add tests for `index.ts`

### ISSUE THREAD

**Issue by WesCossick** [sparksuite/rugged#21]
Add test(s) that mimic the ones we've written here: https://github.com/sparksuite/w3c-css-validator/blob/master/src/index.test.ts.

Basically, these test(s) just need to verify that things are being exported properly. This will help improve the coverage percentage.

**Comment by corymharper** [comment]
In the current design, the only things exported from `index.ts` are types, while the rest of the file is dedicated to asynchronously executing the steps that it imports. So just to confirm, to resolve this issue are we just adding tests to confirm those types are being exported, or is the intent to test that the individual steps are being exported as expected? 

The title of the issue would indicate to me that the former was the case, but looking at the example provided it makes me think we want to test the export of the individual steps.

**Comment by WesCossick** [comment]
You're right, this project won't be a suitable case for adding tests like we did at: https://github.com/sparksuite/w3c-css-validator/blob/master/src/index.test.ts. We can close this issue.
