### ISSUE TITLE
Gracefully handle config file errors

### ISSUE THREAD

**Issue by WesCossick** [sparksuite/rugged#42]
Here's an error compiling a TypeScript config file:

<img width="1108" alt="Screen Shot 2021-03-11 at 2 02 51 PM" src="https://user-images.githubusercontent.com/3850064/110847384-7a9e2800-8272-11eb-8781-45ea3ca0b19e.png">

We should catch this, and not consider it an "unexpected error."

Also, we should do the same for any error in a `.js` config file, too.

**Comment by corymharper** [comment]
Do we want to include the error message in the error we print, or do we want to just print something like "An error was encountered while trying to compile rugged.config.ts"?

**Comment by WesCossick** [comment]
> Do we want to include the error message in the error we print, or do we want to just print something like "An error was encountered while trying to compile rugged.config.ts"?

If it's easy to do so, it'd be helpful to print the specific error message we got. But do so in a visually-appealing way.

**Comment by corymharper** [comment]
> > Do we want to include the error message in the error we print, or do we want to just print something like "An error was encountered while trying to compile rugged.config.ts"?
> 
> If it's easy to do so, it'd be helpful to print the specific error message we got. But do so in a visually-appealing way.

The hard part would be consistent styling, the TS compiler formats it's errors by itself in it's own way, in comparison JS errors are quite terse. Here's a couple of screenshots, the first from a TS config error and the other from a JS config error:

<img width="762" alt="Screen Shot 2021-03-11 at 4 47 59 PM" src="https://user-images.githubusercontent.com/42228018/110866006-1d15d580-828a-11eb-8d02-dd81575e9bd9.png">
<img width="598" alt="Screen Shot 2021-03-11 at 4 50 10 PM" src="https://user-images.githubusercontent.com/42228018/110866008-1dae6c00-828a-11eb-8d9d-c90a394bd18c.png">

**Comment by WesCossick** [comment]
Hmm, that looks pretty reasonable to me. What appears in the terminal before and after those screenshots, though?

**Comment by corymharper** [comment]
> Hmm, that looks pretty reasonable to me. What appears in the terminal before and after those screenshots, though?

<img width="770" alt="Screen Shot 2021-03-11 at 6 06 27 PM" src="https://user-images.githubusercontent.com/42228018/110871769-987c8480-8294-11eb-8b22-1779da26467a.png">
<img width="580" alt="Screen Shot 2021-03-11 at 6 06 43 PM" src="https://user-images.githubusercontent.com/42228018/110871772-99adb180-8294-11eb-826e-d1e17c3d591d.png">

**Comment by WesCossick** [comment]
Yeah, looks good to me!
